// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl5t4cJHwuphbV5nKF-gTkhRnK7XyAtpU',
    appId: '1:432126478057:web:8ece536fddc6e24fc05278',
    messagingSenderId: '432126478057',
    projectId: 'todo-app-9dddf',
    authDomain: 'todo-app-9dddf.firebaseapp.com',
    storageBucket: 'todo-app-9dddf.appspot.com',
    measurementId: 'G-RNLTB0K2YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6jct7vB4AH0RiBVBJPrH3pn4-N79Xdw',
    appId: '1:432126478057:android:544aa8bc786972a3c05278',
    messagingSenderId: '432126478057',
    projectId: 'todo-app-9dddf',
    storageBucket: 'todo-app-9dddf.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl5t4cJHwuphbV5nKF-gTkhRnK7XyAtpU',
    appId: '1:432126478057:web:3cfca3c3c59bc644c05278',
    messagingSenderId: '432126478057',
    projectId: 'todo-app-9dddf',
    authDomain: 'todo-app-9dddf.firebaseapp.com',
    storageBucket: 'todo-app-9dddf.appspot.com',
    measurementId: 'G-K211GXY9JF',
  );
}
